### PR TITLE
In case of multiple files the handler should be called only once.

### PR DESCRIPTION
**Pull request by roonel**
If multiple files are dropped it will only call the handler once (with an array which contains all the uploaded files) instead of calling it for every single file

### CODE REVIEW

**Comment by marcoliceti** [comment]
Hi Mark, thank you for your contribution. You're probably right. While the current behavior still allows you to collect the files inside your handler, it also makes it impossible to know if a call to the handler is the last one for a given folder, which is indeed upsetting.

But... unfortunately I cannot merge your contribution right away. When I released this module I didn't provide an official API. My concern is that changing the behavior of the folder selector could break other developers' code.

I think the right way to do this is to add an option to turn on this behavior. Something like:

```html
<button msl-folder-input="myHandler" msl-folder-input-call-once>
    Select file
</button>
```

Would you like to implement this?

**Comment by roonel** [comment]
Hi Marco!

I'm glad you agree with me and your concerns are grounded.
I like your idea about manually turning it on and I think I can come up with a new version very soon. 

Thanks for your input!

**Comment by marcoliceti** [comment]
Very good. There's still a little issue, though:

```javascript
allFiles = roots.length;
```

This is fine for folders containing only files. What about nested folders?

I suggest the following fix / refactor:

1. Add a second parameter to `exploreFolder`: a `what_to_do` handler function. This function should be applied to each file.
2. If `callOnce` is `false`, `what_to_do` will be something like `function (file) { scope[handler]([file]); }`. Then you just call `exploreFolder` on each root and you're done.
3. Otherwise, if `callOnce` is `true`, `what_to_do` will be something like `function (file) { selected_files.push(file); }`, with `selected_files` being an initially empty array. Then you call `exploreFolder` on each root. Finally, you call `scope[handler]` with `selected_files` as argument.

**Note:** If you have any trouble, I'm here to help. If you don't have time to do it, just tell me and I'll implement it by myself. I'm just trying to make you participate.

**Comment by roonel** [comment]
Ah, I totally forgot about nested folders.  I'll look into it and probably can provide a solution this week. 

Thanks, I have some free time on me and my angular skill needs some polishing so I'll gladly implement it. And thanks for your tips.

**Comment by marcoliceti** [comment]
Hi Mark, thank you for your new contribution. Actually, I was asking for something like this:

```javascript
function exploreFolder(item, what_to_do) {
  if (item.isFile) {
    item.file(function (file) {
      scope.$apply(function () { what_to_do(file); });
    });
  } else if (item.isDirectory) {
    var directory_reader = item.createReader();
      directory_reader.readEntries(function(entries) {
      for (var i = 0; i < entries.length; i++) {
        var entry = entries[i];
        exploreFolder(entry, what_to_do);
      }
      });
  }
}
```

Basically, it's very much like the original implementation, before your pull request. I just added the `what_to_do` parameter, which replaces `scope[handler]`.

Of course you need to pass a suitable value for `what_to_do` based on the `call_once` option:

```javascript
if (folderUploadAvailable()) {
  var roots = event.dataTransfer.items;
  for (var i = 0; i < roots.length; i++) {
    var root = roots[i].webkitGetAsEntry();
    if (call_once) {
      var selected_files = [];
      exploreFolder(root, function (file) {
        selected_files.push(file);
      });
    } else exploreFolder(root, function (file) {
      scope[handler]([file]);
    });
  }
}
```

In other words, no need to count the number of processed files VS total number of files, which could be error prone.

Would you like to start from scratch and apply this strategy?

By the way, a couple of additional notes about JavaScript best practices:

* don't forget `var` when you initialize a variable, otherwise it will become a global variable
* use `===` instead of `==` as much as possible

**Comment by marcoliceti** [comment]
Also, I should add that my strategy is correct only if the [`file` method](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemFileEntry/file) is synchronous, which is something that has to be verified, I honestly don't know.

**Pull request closed without merging**
